### ISSUE TITLE
Getting UPDATE_ROLLBACK_FAILED when running sls deploy after pruning

### ISSUE THREAD

**Issue by gtennis** [claygregory/serverless-prune-plugin#2] opened 2017-04-25 09:24 UTC
Hi,

First, awesome plugin! I'm using serverless 1.9.0 and did 'sls prune -n=1', however, I cannot deploy my lambdas anymore because I'm getting UPDATE_ROLLBACK_FAILED and my CloudFormation on AWS dashboard is broken. Any ideas? As the project is not in production yet, it's ok to remove and recreate the stack again, but that would cause some problems if that would happen on production.

**Comment by claygregory** [comment] 2017-04-25 20:03
Ooh, that sounds like a rather nasty bug! The plugin *shouldn't* be deleting any CloudFormation managed resources, only versions within. But if it is, that would trigger such an error. I can't say I've encountered this before, but I'll try to investigate and see if I can reproduce.

I'm traveling this week and left laptop at home to force myself to disconnect for a few days, but I'll definitely get back with you next week!

**Comment by claygregory** [comment] 2017-05-08 00:49
Hi @gtennis,

So terribly sorry for the delay in getting back with you.

I've tried recreating this issue with a simple hello-world'ish Serverless project and unable to reproduce — any guidance on your situation that may point me in the right direction would be appreciated.

**Comment by dougmoscrop** [comment] 2017-08-26 00:05
You probably want to look at your CloudFormation Stack, and under the Events section, see what happened.. lots of things could cause it to fail not necessarily caused by this plugin.

**Comment by claygregory** [comment] 2017-08-27 22:29
@dougmoscrop Great advice. I'm going to close this issue, as it doesn't seem plugin is cause. @gtennis Feel free to reopen if you confirm an issue that needs addressed in plugin. Thanks!

**Closed by claygregory** 2017-08-27 22:29 UTC
