### ISSUE TITLE
 Serverless Warning - CLI Options upgraded, missing type definitions

### ISSUE THREAD

**Issue by allanice001** [claygregory/serverless-prune-plugin#42] opened 2022-02-24 22:42 UTC
$ node --version
v16.13.1

$ npm --version
8.1.2

Packages Used:
 "serverless": "^2.52.1",
 "serverless-prune-versions": "^1.0.4",
    
 CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
   - PrunePlugin for "number", "stage", "region", "function", "layer", "includeLayers", "dryRun"

  Please report this issue in plugin issue tracker.

**Comment by claygregory** [comment] 2022-02-25 02:33
Duplicate of #29, #34. Please update to a more recent version of the plugin. Type definitions were added in [plugin version 1.5.0](https://github.com/claygregory/serverless-prune-plugin/releases/tag/v.1.5.0).

**Closed by claygregory** 2022-02-25 02:33 UTC
